// flow-typed signature: d74579b0cdd4589518800fc2435487d5
// flow-typed version: <<STUB>>/babel-plugin-minify-mangle-names_v^0.5.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-minify-mangle-names'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-minify-mangle-names' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-minify-mangle-names/lib/bfs-traverse' {
  declare module.exports: any;
}

declare module 'babel-plugin-minify-mangle-names/lib/charset' {
  declare module.exports: any;
}

declare module 'babel-plugin-minify-mangle-names/lib/counted-set' {
  declare module.exports: any;
}

declare module 'babel-plugin-minify-mangle-names/lib/fixup-var-scoping' {
  declare module.exports: any;
}

declare module 'babel-plugin-minify-mangle-names/lib/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-minify-mangle-names/lib/is-label-identifier' {
  declare module.exports: any;
}

declare module 'babel-plugin-minify-mangle-names/lib/scope-tracker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-minify-mangle-names/lib/bfs-traverse.js' {
  declare module.exports: $Exports<'babel-plugin-minify-mangle-names/lib/bfs-traverse'>;
}
declare module 'babel-plugin-minify-mangle-names/lib/charset.js' {
  declare module.exports: $Exports<'babel-plugin-minify-mangle-names/lib/charset'>;
}
declare module 'babel-plugin-minify-mangle-names/lib/counted-set.js' {
  declare module.exports: $Exports<'babel-plugin-minify-mangle-names/lib/counted-set'>;
}
declare module 'babel-plugin-minify-mangle-names/lib/fixup-var-scoping.js' {
  declare module.exports: $Exports<'babel-plugin-minify-mangle-names/lib/fixup-var-scoping'>;
}
declare module 'babel-plugin-minify-mangle-names/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-minify-mangle-names/lib/index'>;
}
declare module 'babel-plugin-minify-mangle-names/lib/is-label-identifier.js' {
  declare module.exports: $Exports<'babel-plugin-minify-mangle-names/lib/is-label-identifier'>;
}
declare module 'babel-plugin-minify-mangle-names/lib/scope-tracker.js' {
  declare module.exports: $Exports<'babel-plugin-minify-mangle-names/lib/scope-tracker'>;
}
