// flow-typed signature: 9b251f42659f4811bcc8c1b46e6d180d
// flow-typed version: <<STUB>>/bitcoin-source_vfile:../bitcoin-source/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bitcoin-source'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bitcoin-source' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bitcoin-source/dist/bitcoin-source.browser' {
  declare module.exports: any;
}

declare module 'bitcoin-source/dist/bitcoin-source.browser.min' {
  declare module.exports: any;
}

declare module 'bitcoin-source/dist/bitcoin-source.common' {
  declare module.exports: any;
}

declare module 'bitcoin-source/dist/bitcoin-source.common.min' {
  declare module.exports: any;
}

declare module 'bitcoin-source/dist/bitcoin-source.esm' {
  declare module.exports: any;
}

declare module 'bitcoin-source/dist/bitcoin-source.esm.min' {
  declare module.exports: any;
}

declare module 'bitcoin-source/flow-typed/npm/@babel/core_vx.x.x' {
  declare module.exports: any;
}

declare module 'bitcoin-source/flow-typed/npm/@babel/preset-env_vx.x.x' {
  declare module.exports: any;
}

declare module 'bitcoin-source/flow-typed/npm/@babel/preset-flow_vx.x.x' {
  declare module.exports: any;
}

declare module 'bitcoin-source/flow-typed/npm/@babel/register_v7.x.x' {
  declare module.exports: any;
}

declare module 'bitcoin-source/flow-typed/npm/babel-eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'bitcoin-source/flow-typed/npm/babel-preset-minify_vx.x.x' {
  declare module.exports: any;
}

declare module 'bitcoin-source/flow-typed/npm/big-integer_vx.x.x' {
  declare module.exports: any;
}

declare module 'bitcoin-source/flow-typed/npm/bn.js_vx.x.x' {
  declare module.exports: any;
}

declare module 'bitcoin-source/flow-typed/npm/bs58_vx.x.x' {
  declare module.exports: any;
}

declare module 'bitcoin-source/flow-typed/npm/buffer-compare_vx.x.x' {
  declare module.exports: any;
}

declare module 'bitcoin-source/flow-typed/npm/cashaddrjs_vx.x.x' {
  declare module.exports: any;
}

declare module 'bitcoin-source/flow-typed/npm/chai_vx.x.x' {
  declare module.exports: any;
}

declare module 'bitcoin-source/flow-typed/npm/elliptic_vx.x.x' {
  declare module.exports: any;
}

declare module 'bitcoin-source/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'bitcoin-source/flow-typed/npm/eslint-config-airbnb-base_vx.x.x' {
  declare module.exports: any;
}

declare module 'bitcoin-source/flow-typed/npm/eslint-config-prettier_vx.x.x' {
  declare module.exports: any;
}

declare module 'bitcoin-source/flow-typed/npm/eslint-plugin-flowtype_vx.x.x' {
  declare module.exports: any;
}

declare module 'bitcoin-source/flow-typed/npm/eslint-plugin-flowtype-errors_vx.x.x' {
  declare module.exports: any;
}

declare module 'bitcoin-source/flow-typed/npm/eslint-plugin-import_vx.x.x' {
  declare module.exports: any;
}

declare module 'bitcoin-source/flow-typed/npm/eslint-plugin-prettier_vx.x.x' {
  declare module.exports: any;
}

declare module 'bitcoin-source/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'bitcoin-source/flow-typed/npm/flow-copy-source_vx.x.x' {
  declare module.exports: any;
}

declare module 'bitcoin-source/flow-typed/npm/flow-typed_vx.x.x' {
  declare module.exports: any;
}

declare module 'bitcoin-source/flow-typed/npm/hash.js_vx.x.x' {
  declare module.exports: any;
}

declare module 'bitcoin-source/flow-typed/npm/jsdoc_vx.x.x' {
  declare module.exports: any;
}

declare module 'bitcoin-source/flow-typed/npm/lodash_v4.x.x' {
  declare module.exports: any;
}

declare module 'bitcoin-source/flow-typed/npm/mocha_v6.x.x' {
  declare module.exports: any;
}

declare module 'bitcoin-source/flow-typed/npm/mustache_vx.x.x' {
  declare module.exports: any;
}

declare module 'bitcoin-source/flow-typed/npm/nyc_vx.x.x' {
  declare module.exports: any;
}

declare module 'bitcoin-source/flow-typed/npm/prettier_v1.x.x' {
  declare module.exports: any;
}

declare module 'bitcoin-source/flow-typed/npm/randombytes_vx.x.x' {
  declare module.exports: any;
}

declare module 'bitcoin-source/flow-typed/npm/rollup_vx.x.x' {
  declare module.exports: any;
}

declare module 'bitcoin-source/flow-typed/npm/rollup-plugin-babel_vx.x.x' {
  declare module.exports: any;
}

declare module 'bitcoin-source/flow-typed/npm/rollup-plugin-commonjs_vx.x.x' {
  declare module.exports: any;
}

declare module 'bitcoin-source/flow-typed/npm/rollup-plugin-flow_vx.x.x' {
  declare module.exports: any;
}

declare module 'bitcoin-source/flow-typed/npm/rollup-plugin-json_vx.x.x' {
  declare module.exports: any;
}

declare module 'bitcoin-source/flow-typed/npm/rollup-plugin-node-builtins_vx.x.x' {
  declare module.exports: any;
}

declare module 'bitcoin-source/flow-typed/npm/rollup-plugin-node-globals_vx.x.x' {
  declare module.exports: any;
}

declare module 'bitcoin-source/flow-typed/npm/rollup-plugin-node-resolve_vx.x.x' {
  declare module.exports: any;
}

declare module 'bitcoin-source/flow-typed/npm/rollup-plugin-terser_vx.x.x' {
  declare module.exports: any;
}

declare module 'bitcoin-source/flow-typed/npm/sinon_vx.x.x' {
  declare module.exports: any;
}

declare module 'bitcoin-source/flow-typed/npm/uglify-js_vx.x.x' {
  declare module.exports: any;
}

declare module 'bitcoin-source/flow-typed/npm/unorm_vx.x.x' {
  declare module.exports: any;
}

declare module 'bitcoin-source/rollup.config' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/address' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/block/block' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/block/blockheader' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/block/merkleblock' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/crypto/bn' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/crypto/ecdsa' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/crypto/hash' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/crypto/point' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/crypto/random' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/crypto/signature' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/encoding/base58' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/encoding/base58check' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/encoding/bufferreader' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/encoding/bufferwriter' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/encoding/varint' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/errors/index' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/errors/spec' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/hdprivatekey' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/hdpublickey' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/index' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/message' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/mnemonic/index' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/mnemonic/mnemonic' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/mnemonic/pbkdf2' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/mnemonic/words/chinese' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/mnemonic/words/english' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/mnemonic/words/french' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/mnemonic/words/index' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/mnemonic/words/italian' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/mnemonic/words/japanese' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/mnemonic/words/spanish' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/networks' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/opcode' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/privatekey' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/publickey' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/script/interpreter' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/script/script' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/transaction/input/input' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/transaction/input/multisig' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/transaction/input/multisigscripthash' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/transaction/input/publickey' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/transaction/input/publickeyhash' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/transaction/input/scripthash' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/transaction/output-id' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/transaction/output' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/transaction/sighash' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/transaction/signature' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/transaction/transaction' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/transaction/unspentoutput' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/unit' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/uri' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/util/buffer' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/util/js' {
  declare module.exports: any;
}

declare module 'bitcoin-source/src/util/preconditions' {
  declare module.exports: any;
}

declare module 'bitcoin-source/test/address' {
  declare module.exports: any;
}

declare module 'bitcoin-source/test/bitcoin' {
  declare module.exports: any;
}

declare module 'bitcoin-source/test/block/block' {
  declare module.exports: any;
}

declare module 'bitcoin-source/test/block/blockheader' {
  declare module.exports: any;
}

declare module 'bitcoin-source/test/block/merkleblock' {
  declare module.exports: any;
}

declare module 'bitcoin-source/test/crypto/bn' {
  declare module.exports: any;
}

declare module 'bitcoin-source/test/crypto/ecdsa' {
  declare module.exports: any;
}

declare module 'bitcoin-source/test/crypto/hash' {
  declare module.exports: any;
}

declare module 'bitcoin-source/test/crypto/point' {
  declare module.exports: any;
}

declare module 'bitcoin-source/test/crypto/random' {
  declare module.exports: any;
}

declare module 'bitcoin-source/test/crypto/signature' {
  declare module.exports: any;
}

declare module 'bitcoin-source/test/data/blk86756-testnet' {
  declare module.exports: any;
}

declare module 'bitcoin-source/test/data/merkleblocks' {
  declare module.exports: any;
}

declare module 'bitcoin-source/test/docs' {
  declare module.exports: any;
}

declare module 'bitcoin-source/test/encoding/base58' {
  declare module.exports: any;
}

declare module 'bitcoin-source/test/encoding/base58check' {
  declare module.exports: any;
}

declare module 'bitcoin-source/test/encoding/bufferreader' {
  declare module.exports: any;
}

declare module 'bitcoin-source/test/encoding/bufferwriter' {
  declare module.exports: any;
}

declare module 'bitcoin-source/test/encoding/varint' {
  declare module.exports: any;
}

declare module 'bitcoin-source/test/hdkeys' {
  declare module.exports: any;
}

declare module 'bitcoin-source/test/hdprivatekey' {
  declare module.exports: any;
}

declare module 'bitcoin-source/test/hdpublickey' {
  declare module.exports: any;
}

declare module 'bitcoin-source/test/message' {
  declare module.exports: any;
}

declare module 'bitcoin-source/test/mnemonic/mnemonic' {
  declare module.exports: any;
}

declare module 'bitcoin-source/test/mnemonic/pbkdf2' {
  declare module.exports: any;
}

declare module 'bitcoin-source/test/networks' {
  declare module.exports: any;
}

declare module 'bitcoin-source/test/opcode' {
  declare module.exports: any;
}

declare module 'bitcoin-source/test/privatekey' {
  declare module.exports: any;
}

declare module 'bitcoin-source/test/publickey' {
  declare module.exports: any;
}

declare module 'bitcoin-source/test/script/interpreter' {
  declare module.exports: any;
}

declare module 'bitcoin-source/test/script/script' {
  declare module.exports: any;
}

declare module 'bitcoin-source/test/transaction/deserialize' {
  declare module.exports: any;
}

declare module 'bitcoin-source/test/transaction/input/input' {
  declare module.exports: any;
}

declare module 'bitcoin-source/test/transaction/input/multisig' {
  declare module.exports: any;
}

declare module 'bitcoin-source/test/transaction/input/multisigscripthash' {
  declare module.exports: any;
}

declare module 'bitcoin-source/test/transaction/input/publickey' {
  declare module.exports: any;
}

declare module 'bitcoin-source/test/transaction/input/publickeyhash' {
  declare module.exports: any;
}

declare module 'bitcoin-source/test/transaction/output-id' {
  declare module.exports: any;
}

declare module 'bitcoin-source/test/transaction/output' {
  declare module.exports: any;
}

declare module 'bitcoin-source/test/transaction/sighash' {
  declare module.exports: any;
}

declare module 'bitcoin-source/test/transaction/signature' {
  declare module.exports: any;
}

declare module 'bitcoin-source/test/transaction/transaction' {
  declare module.exports: any;
}

declare module 'bitcoin-source/test/transaction/unspentoutput' {
  declare module.exports: any;
}

declare module 'bitcoin-source/test/unit' {
  declare module.exports: any;
}

declare module 'bitcoin-source/test/uri' {
  declare module.exports: any;
}

declare module 'bitcoin-source/test/util/buffer' {
  declare module.exports: any;
}

declare module 'bitcoin-source/test/util/js' {
  declare module.exports: any;
}

declare module 'bitcoin-source/test/util/preconditions' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bitcoin-source/dist/bitcoin-source.browser.js' {
  declare module.exports: $Exports<'bitcoin-source/dist/bitcoin-source.browser'>;
}
declare module 'bitcoin-source/dist/bitcoin-source.browser.min.js' {
  declare module.exports: $Exports<'bitcoin-source/dist/bitcoin-source.browser.min'>;
}
declare module 'bitcoin-source/dist/bitcoin-source.common.js' {
  declare module.exports: $Exports<'bitcoin-source/dist/bitcoin-source.common'>;
}
declare module 'bitcoin-source/dist/bitcoin-source.common.min.js' {
  declare module.exports: $Exports<'bitcoin-source/dist/bitcoin-source.common.min'>;
}
declare module 'bitcoin-source/dist/bitcoin-source.esm.js' {
  declare module.exports: $Exports<'bitcoin-source/dist/bitcoin-source.esm'>;
}
declare module 'bitcoin-source/dist/bitcoin-source.esm.min.js' {
  declare module.exports: $Exports<'bitcoin-source/dist/bitcoin-source.esm.min'>;
}
declare module 'bitcoin-source/flow-typed/npm/@babel/core_vx.x.x.js' {
  declare module.exports: $Exports<'bitcoin-source/flow-typed/npm/@babel/core_vx.x.x'>;
}
declare module 'bitcoin-source/flow-typed/npm/@babel/preset-env_vx.x.x.js' {
  declare module.exports: $Exports<'bitcoin-source/flow-typed/npm/@babel/preset-env_vx.x.x'>;
}
declare module 'bitcoin-source/flow-typed/npm/@babel/preset-flow_vx.x.x.js' {
  declare module.exports: $Exports<'bitcoin-source/flow-typed/npm/@babel/preset-flow_vx.x.x'>;
}
declare module 'bitcoin-source/flow-typed/npm/@babel/register_v7.x.x.js' {
  declare module.exports: $Exports<'bitcoin-source/flow-typed/npm/@babel/register_v7.x.x'>;
}
declare module 'bitcoin-source/flow-typed/npm/babel-eslint_vx.x.x.js' {
  declare module.exports: $Exports<'bitcoin-source/flow-typed/npm/babel-eslint_vx.x.x'>;
}
declare module 'bitcoin-source/flow-typed/npm/babel-preset-minify_vx.x.x.js' {
  declare module.exports: $Exports<'bitcoin-source/flow-typed/npm/babel-preset-minify_vx.x.x'>;
}
declare module 'bitcoin-source/flow-typed/npm/big-integer_vx.x.x.js' {
  declare module.exports: $Exports<'bitcoin-source/flow-typed/npm/big-integer_vx.x.x'>;
}
declare module 'bitcoin-source/flow-typed/npm/bn.js_vx.x.x.js' {
  declare module.exports: $Exports<'bitcoin-source/flow-typed/npm/bn.js_vx.x.x'>;
}
declare module 'bitcoin-source/flow-typed/npm/bs58_vx.x.x.js' {
  declare module.exports: $Exports<'bitcoin-source/flow-typed/npm/bs58_vx.x.x'>;
}
declare module 'bitcoin-source/flow-typed/npm/buffer-compare_vx.x.x.js' {
  declare module.exports: $Exports<'bitcoin-source/flow-typed/npm/buffer-compare_vx.x.x'>;
}
declare module 'bitcoin-source/flow-typed/npm/cashaddrjs_vx.x.x.js' {
  declare module.exports: $Exports<'bitcoin-source/flow-typed/npm/cashaddrjs_vx.x.x'>;
}
declare module 'bitcoin-source/flow-typed/npm/chai_vx.x.x.js' {
  declare module.exports: $Exports<'bitcoin-source/flow-typed/npm/chai_vx.x.x'>;
}
declare module 'bitcoin-source/flow-typed/npm/elliptic_vx.x.x.js' {
  declare module.exports: $Exports<'bitcoin-source/flow-typed/npm/elliptic_vx.x.x'>;
}
declare module 'bitcoin-source/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'bitcoin-source/flow-typed/npm/eslint_vx.x.x'>;
}
declare module 'bitcoin-source/flow-typed/npm/eslint-config-airbnb-base_vx.x.x.js' {
  declare module.exports: $Exports<'bitcoin-source/flow-typed/npm/eslint-config-airbnb-base_vx.x.x'>;
}
declare module 'bitcoin-source/flow-typed/npm/eslint-config-prettier_vx.x.x.js' {
  declare module.exports: $Exports<'bitcoin-source/flow-typed/npm/eslint-config-prettier_vx.x.x'>;
}
declare module 'bitcoin-source/flow-typed/npm/eslint-plugin-flowtype_vx.x.x.js' {
  declare module.exports: $Exports<'bitcoin-source/flow-typed/npm/eslint-plugin-flowtype_vx.x.x'>;
}
declare module 'bitcoin-source/flow-typed/npm/eslint-plugin-flowtype-errors_vx.x.x.js' {
  declare module.exports: $Exports<'bitcoin-source/flow-typed/npm/eslint-plugin-flowtype-errors_vx.x.x'>;
}
declare module 'bitcoin-source/flow-typed/npm/eslint-plugin-import_vx.x.x.js' {
  declare module.exports: $Exports<'bitcoin-source/flow-typed/npm/eslint-plugin-import_vx.x.x'>;
}
declare module 'bitcoin-source/flow-typed/npm/eslint-plugin-prettier_vx.x.x.js' {
  declare module.exports: $Exports<'bitcoin-source/flow-typed/npm/eslint-plugin-prettier_vx.x.x'>;
}
declare module 'bitcoin-source/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'bitcoin-source/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'bitcoin-source/flow-typed/npm/flow-copy-source_vx.x.x.js' {
  declare module.exports: $Exports<'bitcoin-source/flow-typed/npm/flow-copy-source_vx.x.x'>;
}
declare module 'bitcoin-source/flow-typed/npm/flow-typed_vx.x.x.js' {
  declare module.exports: $Exports<'bitcoin-source/flow-typed/npm/flow-typed_vx.x.x'>;
}
declare module 'bitcoin-source/flow-typed/npm/hash.js_vx.x.x.js' {
  declare module.exports: $Exports<'bitcoin-source/flow-typed/npm/hash.js_vx.x.x'>;
}
declare module 'bitcoin-source/flow-typed/npm/jsdoc_vx.x.x.js' {
  declare module.exports: $Exports<'bitcoin-source/flow-typed/npm/jsdoc_vx.x.x'>;
}
declare module 'bitcoin-source/flow-typed/npm/lodash_v4.x.x.js' {
  declare module.exports: $Exports<'bitcoin-source/flow-typed/npm/lodash_v4.x.x'>;
}
declare module 'bitcoin-source/flow-typed/npm/mocha_v6.x.x.js' {
  declare module.exports: $Exports<'bitcoin-source/flow-typed/npm/mocha_v6.x.x'>;
}
declare module 'bitcoin-source/flow-typed/npm/mustache_vx.x.x.js' {
  declare module.exports: $Exports<'bitcoin-source/flow-typed/npm/mustache_vx.x.x'>;
}
declare module 'bitcoin-source/flow-typed/npm/nyc_vx.x.x.js' {
  declare module.exports: $Exports<'bitcoin-source/flow-typed/npm/nyc_vx.x.x'>;
}
declare module 'bitcoin-source/flow-typed/npm/prettier_v1.x.x.js' {
  declare module.exports: $Exports<'bitcoin-source/flow-typed/npm/prettier_v1.x.x'>;
}
declare module 'bitcoin-source/flow-typed/npm/randombytes_vx.x.x.js' {
  declare module.exports: $Exports<'bitcoin-source/flow-typed/npm/randombytes_vx.x.x'>;
}
declare module 'bitcoin-source/flow-typed/npm/rollup_vx.x.x.js' {
  declare module.exports: $Exports<'bitcoin-source/flow-typed/npm/rollup_vx.x.x'>;
}
declare module 'bitcoin-source/flow-typed/npm/rollup-plugin-babel_vx.x.x.js' {
  declare module.exports: $Exports<'bitcoin-source/flow-typed/npm/rollup-plugin-babel_vx.x.x'>;
}
declare module 'bitcoin-source/flow-typed/npm/rollup-plugin-commonjs_vx.x.x.js' {
  declare module.exports: $Exports<'bitcoin-source/flow-typed/npm/rollup-plugin-commonjs_vx.x.x'>;
}
declare module 'bitcoin-source/flow-typed/npm/rollup-plugin-flow_vx.x.x.js' {
  declare module.exports: $Exports<'bitcoin-source/flow-typed/npm/rollup-plugin-flow_vx.x.x'>;
}
declare module 'bitcoin-source/flow-typed/npm/rollup-plugin-json_vx.x.x.js' {
  declare module.exports: $Exports<'bitcoin-source/flow-typed/npm/rollup-plugin-json_vx.x.x'>;
}
declare module 'bitcoin-source/flow-typed/npm/rollup-plugin-node-builtins_vx.x.x.js' {
  declare module.exports: $Exports<'bitcoin-source/flow-typed/npm/rollup-plugin-node-builtins_vx.x.x'>;
}
declare module 'bitcoin-source/flow-typed/npm/rollup-plugin-node-globals_vx.x.x.js' {
  declare module.exports: $Exports<'bitcoin-source/flow-typed/npm/rollup-plugin-node-globals_vx.x.x'>;
}
declare module 'bitcoin-source/flow-typed/npm/rollup-plugin-node-resolve_vx.x.x.js' {
  declare module.exports: $Exports<'bitcoin-source/flow-typed/npm/rollup-plugin-node-resolve_vx.x.x'>;
}
declare module 'bitcoin-source/flow-typed/npm/rollup-plugin-terser_vx.x.x.js' {
  declare module.exports: $Exports<'bitcoin-source/flow-typed/npm/rollup-plugin-terser_vx.x.x'>;
}
declare module 'bitcoin-source/flow-typed/npm/sinon_vx.x.x.js' {
  declare module.exports: $Exports<'bitcoin-source/flow-typed/npm/sinon_vx.x.x'>;
}
declare module 'bitcoin-source/flow-typed/npm/uglify-js_vx.x.x.js' {
  declare module.exports: $Exports<'bitcoin-source/flow-typed/npm/uglify-js_vx.x.x'>;
}
declare module 'bitcoin-source/flow-typed/npm/unorm_vx.x.x.js' {
  declare module.exports: $Exports<'bitcoin-source/flow-typed/npm/unorm_vx.x.x'>;
}
declare module 'bitcoin-source/rollup.config.js' {
  declare module.exports: $Exports<'bitcoin-source/rollup.config'>;
}
declare module 'bitcoin-source/src/address.js' {
  declare module.exports: $Exports<'bitcoin-source/src/address'>;
}
declare module 'bitcoin-source/src/block/block.js' {
  declare module.exports: $Exports<'bitcoin-source/src/block/block'>;
}
declare module 'bitcoin-source/src/block/blockheader.js' {
  declare module.exports: $Exports<'bitcoin-source/src/block/blockheader'>;
}
declare module 'bitcoin-source/src/block/merkleblock.js' {
  declare module.exports: $Exports<'bitcoin-source/src/block/merkleblock'>;
}
declare module 'bitcoin-source/src/crypto/bn.js' {
  declare module.exports: $Exports<'bitcoin-source/src/crypto/bn'>;
}
declare module 'bitcoin-source/src/crypto/ecdsa.js' {
  declare module.exports: $Exports<'bitcoin-source/src/crypto/ecdsa'>;
}
declare module 'bitcoin-source/src/crypto/hash.js' {
  declare module.exports: $Exports<'bitcoin-source/src/crypto/hash'>;
}
declare module 'bitcoin-source/src/crypto/point.js' {
  declare module.exports: $Exports<'bitcoin-source/src/crypto/point'>;
}
declare module 'bitcoin-source/src/crypto/random.js' {
  declare module.exports: $Exports<'bitcoin-source/src/crypto/random'>;
}
declare module 'bitcoin-source/src/crypto/signature.js' {
  declare module.exports: $Exports<'bitcoin-source/src/crypto/signature'>;
}
declare module 'bitcoin-source/src/encoding/base58.js' {
  declare module.exports: $Exports<'bitcoin-source/src/encoding/base58'>;
}
declare module 'bitcoin-source/src/encoding/base58check.js' {
  declare module.exports: $Exports<'bitcoin-source/src/encoding/base58check'>;
}
declare module 'bitcoin-source/src/encoding/bufferreader.js' {
  declare module.exports: $Exports<'bitcoin-source/src/encoding/bufferreader'>;
}
declare module 'bitcoin-source/src/encoding/bufferwriter.js' {
  declare module.exports: $Exports<'bitcoin-source/src/encoding/bufferwriter'>;
}
declare module 'bitcoin-source/src/encoding/varint.js' {
  declare module.exports: $Exports<'bitcoin-source/src/encoding/varint'>;
}
declare module 'bitcoin-source/src/errors/index.js' {
  declare module.exports: $Exports<'bitcoin-source/src/errors/index'>;
}
declare module 'bitcoin-source/src/errors/spec.js' {
  declare module.exports: $Exports<'bitcoin-source/src/errors/spec'>;
}
declare module 'bitcoin-source/src/hdprivatekey.js' {
  declare module.exports: $Exports<'bitcoin-source/src/hdprivatekey'>;
}
declare module 'bitcoin-source/src/hdpublickey.js' {
  declare module.exports: $Exports<'bitcoin-source/src/hdpublickey'>;
}
declare module 'bitcoin-source/src/index.js' {
  declare module.exports: $Exports<'bitcoin-source/src/index'>;
}
declare module 'bitcoin-source/src/message.js' {
  declare module.exports: $Exports<'bitcoin-source/src/message'>;
}
declare module 'bitcoin-source/src/mnemonic/index.js' {
  declare module.exports: $Exports<'bitcoin-source/src/mnemonic/index'>;
}
declare module 'bitcoin-source/src/mnemonic/mnemonic.js' {
  declare module.exports: $Exports<'bitcoin-source/src/mnemonic/mnemonic'>;
}
declare module 'bitcoin-source/src/mnemonic/pbkdf2.js' {
  declare module.exports: $Exports<'bitcoin-source/src/mnemonic/pbkdf2'>;
}
declare module 'bitcoin-source/src/mnemonic/words/chinese.js' {
  declare module.exports: $Exports<'bitcoin-source/src/mnemonic/words/chinese'>;
}
declare module 'bitcoin-source/src/mnemonic/words/english.js' {
  declare module.exports: $Exports<'bitcoin-source/src/mnemonic/words/english'>;
}
declare module 'bitcoin-source/src/mnemonic/words/french.js' {
  declare module.exports: $Exports<'bitcoin-source/src/mnemonic/words/french'>;
}
declare module 'bitcoin-source/src/mnemonic/words/index.js' {
  declare module.exports: $Exports<'bitcoin-source/src/mnemonic/words/index'>;
}
declare module 'bitcoin-source/src/mnemonic/words/italian.js' {
  declare module.exports: $Exports<'bitcoin-source/src/mnemonic/words/italian'>;
}
declare module 'bitcoin-source/src/mnemonic/words/japanese.js' {
  declare module.exports: $Exports<'bitcoin-source/src/mnemonic/words/japanese'>;
}
declare module 'bitcoin-source/src/mnemonic/words/spanish.js' {
  declare module.exports: $Exports<'bitcoin-source/src/mnemonic/words/spanish'>;
}
declare module 'bitcoin-source/src/networks.js' {
  declare module.exports: $Exports<'bitcoin-source/src/networks'>;
}
declare module 'bitcoin-source/src/opcode.js' {
  declare module.exports: $Exports<'bitcoin-source/src/opcode'>;
}
declare module 'bitcoin-source/src/privatekey.js' {
  declare module.exports: $Exports<'bitcoin-source/src/privatekey'>;
}
declare module 'bitcoin-source/src/publickey.js' {
  declare module.exports: $Exports<'bitcoin-source/src/publickey'>;
}
declare module 'bitcoin-source/src/script/interpreter.js' {
  declare module.exports: $Exports<'bitcoin-source/src/script/interpreter'>;
}
declare module 'bitcoin-source/src/script/script.js' {
  declare module.exports: $Exports<'bitcoin-source/src/script/script'>;
}
declare module 'bitcoin-source/src/transaction/input/input.js' {
  declare module.exports: $Exports<'bitcoin-source/src/transaction/input/input'>;
}
declare module 'bitcoin-source/src/transaction/input/multisig.js' {
  declare module.exports: $Exports<'bitcoin-source/src/transaction/input/multisig'>;
}
declare module 'bitcoin-source/src/transaction/input/multisigscripthash.js' {
  declare module.exports: $Exports<'bitcoin-source/src/transaction/input/multisigscripthash'>;
}
declare module 'bitcoin-source/src/transaction/input/publickey.js' {
  declare module.exports: $Exports<'bitcoin-source/src/transaction/input/publickey'>;
}
declare module 'bitcoin-source/src/transaction/input/publickeyhash.js' {
  declare module.exports: $Exports<'bitcoin-source/src/transaction/input/publickeyhash'>;
}
declare module 'bitcoin-source/src/transaction/input/scripthash.js' {
  declare module.exports: $Exports<'bitcoin-source/src/transaction/input/scripthash'>;
}
declare module 'bitcoin-source/src/transaction/output-id.js' {
  declare module.exports: $Exports<'bitcoin-source/src/transaction/output-id'>;
}
declare module 'bitcoin-source/src/transaction/output.js' {
  declare module.exports: $Exports<'bitcoin-source/src/transaction/output'>;
}
declare module 'bitcoin-source/src/transaction/sighash.js' {
  declare module.exports: $Exports<'bitcoin-source/src/transaction/sighash'>;
}
declare module 'bitcoin-source/src/transaction/signature.js' {
  declare module.exports: $Exports<'bitcoin-source/src/transaction/signature'>;
}
declare module 'bitcoin-source/src/transaction/transaction.js' {
  declare module.exports: $Exports<'bitcoin-source/src/transaction/transaction'>;
}
declare module 'bitcoin-source/src/transaction/unspentoutput.js' {
  declare module.exports: $Exports<'bitcoin-source/src/transaction/unspentoutput'>;
}
declare module 'bitcoin-source/src/unit.js' {
  declare module.exports: $Exports<'bitcoin-source/src/unit'>;
}
declare module 'bitcoin-source/src/uri.js' {
  declare module.exports: $Exports<'bitcoin-source/src/uri'>;
}
declare module 'bitcoin-source/src/util/buffer.js' {
  declare module.exports: $Exports<'bitcoin-source/src/util/buffer'>;
}
declare module 'bitcoin-source/src/util/js.js' {
  declare module.exports: $Exports<'bitcoin-source/src/util/js'>;
}
declare module 'bitcoin-source/src/util/preconditions.js' {
  declare module.exports: $Exports<'bitcoin-source/src/util/preconditions'>;
}
declare module 'bitcoin-source/test/address.js' {
  declare module.exports: $Exports<'bitcoin-source/test/address'>;
}
declare module 'bitcoin-source/test/bitcoin.js' {
  declare module.exports: $Exports<'bitcoin-source/test/bitcoin'>;
}
declare module 'bitcoin-source/test/block/block.js' {
  declare module.exports: $Exports<'bitcoin-source/test/block/block'>;
}
declare module 'bitcoin-source/test/block/blockheader.js' {
  declare module.exports: $Exports<'bitcoin-source/test/block/blockheader'>;
}
declare module 'bitcoin-source/test/block/merkleblock.js' {
  declare module.exports: $Exports<'bitcoin-source/test/block/merkleblock'>;
}
declare module 'bitcoin-source/test/crypto/bn.js' {
  declare module.exports: $Exports<'bitcoin-source/test/crypto/bn'>;
}
declare module 'bitcoin-source/test/crypto/ecdsa.js' {
  declare module.exports: $Exports<'bitcoin-source/test/crypto/ecdsa'>;
}
declare module 'bitcoin-source/test/crypto/hash.js' {
  declare module.exports: $Exports<'bitcoin-source/test/crypto/hash'>;
}
declare module 'bitcoin-source/test/crypto/point.js' {
  declare module.exports: $Exports<'bitcoin-source/test/crypto/point'>;
}
declare module 'bitcoin-source/test/crypto/random.js' {
  declare module.exports: $Exports<'bitcoin-source/test/crypto/random'>;
}
declare module 'bitcoin-source/test/crypto/signature.js' {
  declare module.exports: $Exports<'bitcoin-source/test/crypto/signature'>;
}
declare module 'bitcoin-source/test/data/blk86756-testnet.js' {
  declare module.exports: $Exports<'bitcoin-source/test/data/blk86756-testnet'>;
}
declare module 'bitcoin-source/test/data/merkleblocks.js' {
  declare module.exports: $Exports<'bitcoin-source/test/data/merkleblocks'>;
}
declare module 'bitcoin-source/test/docs.js' {
  declare module.exports: $Exports<'bitcoin-source/test/docs'>;
}
declare module 'bitcoin-source/test/encoding/base58.js' {
  declare module.exports: $Exports<'bitcoin-source/test/encoding/base58'>;
}
declare module 'bitcoin-source/test/encoding/base58check.js' {
  declare module.exports: $Exports<'bitcoin-source/test/encoding/base58check'>;
}
declare module 'bitcoin-source/test/encoding/bufferreader.js' {
  declare module.exports: $Exports<'bitcoin-source/test/encoding/bufferreader'>;
}
declare module 'bitcoin-source/test/encoding/bufferwriter.js' {
  declare module.exports: $Exports<'bitcoin-source/test/encoding/bufferwriter'>;
}
declare module 'bitcoin-source/test/encoding/varint.js' {
  declare module.exports: $Exports<'bitcoin-source/test/encoding/varint'>;
}
declare module 'bitcoin-source/test/hdkeys.js' {
  declare module.exports: $Exports<'bitcoin-source/test/hdkeys'>;
}
declare module 'bitcoin-source/test/hdprivatekey.js' {
  declare module.exports: $Exports<'bitcoin-source/test/hdprivatekey'>;
}
declare module 'bitcoin-source/test/hdpublickey.js' {
  declare module.exports: $Exports<'bitcoin-source/test/hdpublickey'>;
}
declare module 'bitcoin-source/test/message.js' {
  declare module.exports: $Exports<'bitcoin-source/test/message'>;
}
declare module 'bitcoin-source/test/mnemonic/mnemonic.js' {
  declare module.exports: $Exports<'bitcoin-source/test/mnemonic/mnemonic'>;
}
declare module 'bitcoin-source/test/mnemonic/pbkdf2.js' {
  declare module.exports: $Exports<'bitcoin-source/test/mnemonic/pbkdf2'>;
}
declare module 'bitcoin-source/test/networks.js' {
  declare module.exports: $Exports<'bitcoin-source/test/networks'>;
}
declare module 'bitcoin-source/test/opcode.js' {
  declare module.exports: $Exports<'bitcoin-source/test/opcode'>;
}
declare module 'bitcoin-source/test/privatekey.js' {
  declare module.exports: $Exports<'bitcoin-source/test/privatekey'>;
}
declare module 'bitcoin-source/test/publickey.js' {
  declare module.exports: $Exports<'bitcoin-source/test/publickey'>;
}
declare module 'bitcoin-source/test/script/interpreter.js' {
  declare module.exports: $Exports<'bitcoin-source/test/script/interpreter'>;
}
declare module 'bitcoin-source/test/script/script.js' {
  declare module.exports: $Exports<'bitcoin-source/test/script/script'>;
}
declare module 'bitcoin-source/test/transaction/deserialize.js' {
  declare module.exports: $Exports<'bitcoin-source/test/transaction/deserialize'>;
}
declare module 'bitcoin-source/test/transaction/input/input.js' {
  declare module.exports: $Exports<'bitcoin-source/test/transaction/input/input'>;
}
declare module 'bitcoin-source/test/transaction/input/multisig.js' {
  declare module.exports: $Exports<'bitcoin-source/test/transaction/input/multisig'>;
}
declare module 'bitcoin-source/test/transaction/input/multisigscripthash.js' {
  declare module.exports: $Exports<'bitcoin-source/test/transaction/input/multisigscripthash'>;
}
declare module 'bitcoin-source/test/transaction/input/publickey.js' {
  declare module.exports: $Exports<'bitcoin-source/test/transaction/input/publickey'>;
}
declare module 'bitcoin-source/test/transaction/input/publickeyhash.js' {
  declare module.exports: $Exports<'bitcoin-source/test/transaction/input/publickeyhash'>;
}
declare module 'bitcoin-source/test/transaction/output-id.js' {
  declare module.exports: $Exports<'bitcoin-source/test/transaction/output-id'>;
}
declare module 'bitcoin-source/test/transaction/output.js' {
  declare module.exports: $Exports<'bitcoin-source/test/transaction/output'>;
}
declare module 'bitcoin-source/test/transaction/sighash.js' {
  declare module.exports: $Exports<'bitcoin-source/test/transaction/sighash'>;
}
declare module 'bitcoin-source/test/transaction/signature.js' {
  declare module.exports: $Exports<'bitcoin-source/test/transaction/signature'>;
}
declare module 'bitcoin-source/test/transaction/transaction.js' {
  declare module.exports: $Exports<'bitcoin-source/test/transaction/transaction'>;
}
declare module 'bitcoin-source/test/transaction/unspentoutput.js' {
  declare module.exports: $Exports<'bitcoin-source/test/transaction/unspentoutput'>;
}
declare module 'bitcoin-source/test/unit.js' {
  declare module.exports: $Exports<'bitcoin-source/test/unit'>;
}
declare module 'bitcoin-source/test/uri.js' {
  declare module.exports: $Exports<'bitcoin-source/test/uri'>;
}
declare module 'bitcoin-source/test/util/buffer.js' {
  declare module.exports: $Exports<'bitcoin-source/test/util/buffer'>;
}
declare module 'bitcoin-source/test/util/js.js' {
  declare module.exports: $Exports<'bitcoin-source/test/util/js'>;
}
declare module 'bitcoin-source/test/util/preconditions.js' {
  declare module.exports: $Exports<'bitcoin-source/test/util/preconditions'>;
}
