// flow-typed signature: 6471da55b741944bf6d196bcc753033a
// flow-typed version: <<STUB>>/bitcoinsource_v^0.1.16/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bitcoinsource'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bitcoinsource' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bitcoinsource/dist/bitcoinsource.browser' {
  declare module.exports: any;
}

declare module 'bitcoinsource/dist/bitcoinsource.browser.min' {
  declare module.exports: any;
}

declare module 'bitcoinsource/dist/bitcoinsource.common' {
  declare module.exports: any;
}

declare module 'bitcoinsource/dist/bitcoinsource.common.min' {
  declare module.exports: any;
}

declare module 'bitcoinsource/dist/bitcoinsource.esm' {
  declare module.exports: any;
}

declare module 'bitcoinsource/dist/bitcoinsource.esm.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bitcoinsource/dist/bitcoinsource.browser.js' {
  declare module.exports: $Exports<'bitcoinsource/dist/bitcoinsource.browser'>;
}
declare module 'bitcoinsource/dist/bitcoinsource.browser.min.js' {
  declare module.exports: $Exports<'bitcoinsource/dist/bitcoinsource.browser.min'>;
}
declare module 'bitcoinsource/dist/bitcoinsource.common.js' {
  declare module.exports: $Exports<'bitcoinsource/dist/bitcoinsource.common'>;
}
declare module 'bitcoinsource/dist/bitcoinsource.common.min.js' {
  declare module.exports: $Exports<'bitcoinsource/dist/bitcoinsource.common.min'>;
}
declare module 'bitcoinsource/dist/bitcoinsource.esm.js' {
  declare module.exports: $Exports<'bitcoinsource/dist/bitcoinsource.esm'>;
}
declare module 'bitcoinsource/dist/bitcoinsource.esm.min.js' {
  declare module.exports: $Exports<'bitcoinsource/dist/bitcoinsource.esm.min'>;
}
