// flow-typed signature: 1340ee88003c134fa338bda742c07d67
// flow-typed version: <<STUB>>/bitcoinsource_v0.1.12/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bitcoinsource'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bitcoinsource' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bitcoinsource/LICENSE' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/address' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/bitcoinsource' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/block/block' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/block/blockheader' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/block/index' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/block/merkleblock' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/crypto/bn' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/crypto/ecdsa' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/crypto/hash' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/crypto/point' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/crypto/random' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/crypto/signature' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/encoding/base58' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/encoding/base58check' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/encoding/bufferreader' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/encoding/bufferwriter' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/encoding/varint' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/errors/index' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/errors/spec' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/hdprivatekey' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/hdpublickey' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/message' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/mnemonic/index' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/mnemonic/mnemonic' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/mnemonic/pbkdf2' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/mnemonic/words/chinese' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/mnemonic/words/english' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/mnemonic/words/french' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/mnemonic/words/index' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/mnemonic/words/italian' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/mnemonic/words/japanese' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/mnemonic/words/spanish' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/networks' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/opcode' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/privatekey' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/publickey' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/script/index' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/script/interpreter' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/script/script' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/transaction/index' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/transaction/input/index' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/transaction/input/input' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/transaction/input/multisig' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/transaction/input/multisigscripthash' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/transaction/input/publickey' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/transaction/input/publickeyhash' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/transaction/input/scripthash' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/transaction/output' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/transaction/sighash' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/transaction/signature' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/transaction/transaction' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/transaction/unspentoutput' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/unit' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/uri' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/util/buffer' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/util/js' {
  declare module.exports: any;
}

declare module 'bitcoinsource/src/util/preconditions' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bitcoinsource/LICENSE.js' {
  declare module.exports: $Exports<'bitcoinsource/LICENSE'>;
}
declare module 'bitcoinsource/src/address.js' {
  declare module.exports: $Exports<'bitcoinsource/src/address'>;
}
declare module 'bitcoinsource/src/bitcoinsource.js' {
  declare module.exports: $Exports<'bitcoinsource/src/bitcoinsource'>;
}
declare module 'bitcoinsource/src/block/block.js' {
  declare module.exports: $Exports<'bitcoinsource/src/block/block'>;
}
declare module 'bitcoinsource/src/block/blockheader.js' {
  declare module.exports: $Exports<'bitcoinsource/src/block/blockheader'>;
}
declare module 'bitcoinsource/src/block/index.js' {
  declare module.exports: $Exports<'bitcoinsource/src/block/index'>;
}
declare module 'bitcoinsource/src/block/merkleblock.js' {
  declare module.exports: $Exports<'bitcoinsource/src/block/merkleblock'>;
}
declare module 'bitcoinsource/src/crypto/bn.js' {
  declare module.exports: $Exports<'bitcoinsource/src/crypto/bn'>;
}
declare module 'bitcoinsource/src/crypto/ecdsa.js' {
  declare module.exports: $Exports<'bitcoinsource/src/crypto/ecdsa'>;
}
declare module 'bitcoinsource/src/crypto/hash.js' {
  declare module.exports: $Exports<'bitcoinsource/src/crypto/hash'>;
}
declare module 'bitcoinsource/src/crypto/point.js' {
  declare module.exports: $Exports<'bitcoinsource/src/crypto/point'>;
}
declare module 'bitcoinsource/src/crypto/random.js' {
  declare module.exports: $Exports<'bitcoinsource/src/crypto/random'>;
}
declare module 'bitcoinsource/src/crypto/signature.js' {
  declare module.exports: $Exports<'bitcoinsource/src/crypto/signature'>;
}
declare module 'bitcoinsource/src/encoding/base58.js' {
  declare module.exports: $Exports<'bitcoinsource/src/encoding/base58'>;
}
declare module 'bitcoinsource/src/encoding/base58check.js' {
  declare module.exports: $Exports<'bitcoinsource/src/encoding/base58check'>;
}
declare module 'bitcoinsource/src/encoding/bufferreader.js' {
  declare module.exports: $Exports<'bitcoinsource/src/encoding/bufferreader'>;
}
declare module 'bitcoinsource/src/encoding/bufferwriter.js' {
  declare module.exports: $Exports<'bitcoinsource/src/encoding/bufferwriter'>;
}
declare module 'bitcoinsource/src/encoding/varint.js' {
  declare module.exports: $Exports<'bitcoinsource/src/encoding/varint'>;
}
declare module 'bitcoinsource/src/errors/index.js' {
  declare module.exports: $Exports<'bitcoinsource/src/errors/index'>;
}
declare module 'bitcoinsource/src/errors/spec.js' {
  declare module.exports: $Exports<'bitcoinsource/src/errors/spec'>;
}
declare module 'bitcoinsource/src/hdprivatekey.js' {
  declare module.exports: $Exports<'bitcoinsource/src/hdprivatekey'>;
}
declare module 'bitcoinsource/src/hdpublickey.js' {
  declare module.exports: $Exports<'bitcoinsource/src/hdpublickey'>;
}
declare module 'bitcoinsource/src/message.js' {
  declare module.exports: $Exports<'bitcoinsource/src/message'>;
}
declare module 'bitcoinsource/src/mnemonic/index.js' {
  declare module.exports: $Exports<'bitcoinsource/src/mnemonic/index'>;
}
declare module 'bitcoinsource/src/mnemonic/mnemonic.js' {
  declare module.exports: $Exports<'bitcoinsource/src/mnemonic/mnemonic'>;
}
declare module 'bitcoinsource/src/mnemonic/pbkdf2.js' {
  declare module.exports: $Exports<'bitcoinsource/src/mnemonic/pbkdf2'>;
}
declare module 'bitcoinsource/src/mnemonic/words/chinese.js' {
  declare module.exports: $Exports<'bitcoinsource/src/mnemonic/words/chinese'>;
}
declare module 'bitcoinsource/src/mnemonic/words/english.js' {
  declare module.exports: $Exports<'bitcoinsource/src/mnemonic/words/english'>;
}
declare module 'bitcoinsource/src/mnemonic/words/french.js' {
  declare module.exports: $Exports<'bitcoinsource/src/mnemonic/words/french'>;
}
declare module 'bitcoinsource/src/mnemonic/words/index.js' {
  declare module.exports: $Exports<'bitcoinsource/src/mnemonic/words/index'>;
}
declare module 'bitcoinsource/src/mnemonic/words/italian.js' {
  declare module.exports: $Exports<'bitcoinsource/src/mnemonic/words/italian'>;
}
declare module 'bitcoinsource/src/mnemonic/words/japanese.js' {
  declare module.exports: $Exports<'bitcoinsource/src/mnemonic/words/japanese'>;
}
declare module 'bitcoinsource/src/mnemonic/words/spanish.js' {
  declare module.exports: $Exports<'bitcoinsource/src/mnemonic/words/spanish'>;
}
declare module 'bitcoinsource/src/networks.js' {
  declare module.exports: $Exports<'bitcoinsource/src/networks'>;
}
declare module 'bitcoinsource/src/opcode.js' {
  declare module.exports: $Exports<'bitcoinsource/src/opcode'>;
}
declare module 'bitcoinsource/src/privatekey.js' {
  declare module.exports: $Exports<'bitcoinsource/src/privatekey'>;
}
declare module 'bitcoinsource/src/publickey.js' {
  declare module.exports: $Exports<'bitcoinsource/src/publickey'>;
}
declare module 'bitcoinsource/src/script/index.js' {
  declare module.exports: $Exports<'bitcoinsource/src/script/index'>;
}
declare module 'bitcoinsource/src/script/interpreter.js' {
  declare module.exports: $Exports<'bitcoinsource/src/script/interpreter'>;
}
declare module 'bitcoinsource/src/script/script.js' {
  declare module.exports: $Exports<'bitcoinsource/src/script/script'>;
}
declare module 'bitcoinsource/src/transaction/index.js' {
  declare module.exports: $Exports<'bitcoinsource/src/transaction/index'>;
}
declare module 'bitcoinsource/src/transaction/input/index.js' {
  declare module.exports: $Exports<'bitcoinsource/src/transaction/input/index'>;
}
declare module 'bitcoinsource/src/transaction/input/input.js' {
  declare module.exports: $Exports<'bitcoinsource/src/transaction/input/input'>;
}
declare module 'bitcoinsource/src/transaction/input/multisig.js' {
  declare module.exports: $Exports<'bitcoinsource/src/transaction/input/multisig'>;
}
declare module 'bitcoinsource/src/transaction/input/multisigscripthash.js' {
  declare module.exports: $Exports<'bitcoinsource/src/transaction/input/multisigscripthash'>;
}
declare module 'bitcoinsource/src/transaction/input/publickey.js' {
  declare module.exports: $Exports<'bitcoinsource/src/transaction/input/publickey'>;
}
declare module 'bitcoinsource/src/transaction/input/publickeyhash.js' {
  declare module.exports: $Exports<'bitcoinsource/src/transaction/input/publickeyhash'>;
}
declare module 'bitcoinsource/src/transaction/input/scripthash.js' {
  declare module.exports: $Exports<'bitcoinsource/src/transaction/input/scripthash'>;
}
declare module 'bitcoinsource/src/transaction/output.js' {
  declare module.exports: $Exports<'bitcoinsource/src/transaction/output'>;
}
declare module 'bitcoinsource/src/transaction/sighash.js' {
  declare module.exports: $Exports<'bitcoinsource/src/transaction/sighash'>;
}
declare module 'bitcoinsource/src/transaction/signature.js' {
  declare module.exports: $Exports<'bitcoinsource/src/transaction/signature'>;
}
declare module 'bitcoinsource/src/transaction/transaction.js' {
  declare module.exports: $Exports<'bitcoinsource/src/transaction/transaction'>;
}
declare module 'bitcoinsource/src/transaction/unspentoutput.js' {
  declare module.exports: $Exports<'bitcoinsource/src/transaction/unspentoutput'>;
}
declare module 'bitcoinsource/src/unit.js' {
  declare module.exports: $Exports<'bitcoinsource/src/unit'>;
}
declare module 'bitcoinsource/src/uri.js' {
  declare module.exports: $Exports<'bitcoinsource/src/uri'>;
}
declare module 'bitcoinsource/src/util/buffer.js' {
  declare module.exports: $Exports<'bitcoinsource/src/util/buffer'>;
}
declare module 'bitcoinsource/src/util/js.js' {
  declare module.exports: $Exports<'bitcoinsource/src/util/js'>;
}
declare module 'bitcoinsource/src/util/preconditions.js' {
  declare module.exports: $Exports<'bitcoinsource/src/util/preconditions'>;
}
